[experiment]
id = "059f41c8-5d62-4575-929a-a723b3efcdd9"
# a short description that will appear in POPROX dashboards, etc.
description = "Personalized diversity experiment"
start_date = "2025-12-08"
duration = "35 days"

[owner]
team_id = "a3cc2bd4-c75e-4441-b147-c6692c063217"
team_name = "CU POPROX"
# "robin.burke@colorado.edu",
# "Aishwarya.Satwani@colorado.edu",
members = [
  "4a37e16d-a63b-4ff0-b917-9d97299ccea1",
  "7d71dff0-5cef-44f0-9d92-4d85e4ee1afa",
]

[users.groups.control]
minimum_size = 5

[users.groups.diversity]
identical_to = "control"

[users.groups.personalized]
identical_to = "control"

[recommenders.Control]
url = "https://f2q9xa2fvl.execute-api.us-east-1.amazonaws.com?pipeline=control"

[recommenders.TopicDiversity]
url = "https://f2q9xa2fvl.execute-api.us-east-1.amazonaws.com?pipeline=nrms-topic-mmr"

[recommenders.PersonalizedDiversity]
url = "https://f2q9xa2fvl.execute-api.us-east-1.amazonaws.com?pipeline=nrms-topic-mmr-personalized"

[phases]
sequence = ["1"]

[phases.1]
duration = "35 days"

[phases.1.assignments.control]
recommender = "Control"

[phases.1.assignments.diversity]
recommender = "TopicDiversity"

[phases.1.assignments.personalized]
recommender = "PersonalizedDiversity"
